// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQvXMsCQgE5freN9xHNl4qp2xmGxrdLQY',
    appId: '1:857898979788:web:ac2173774096d5d12fcd69',
    messagingSenderId: '857898979788',
    projectId: 'fortune-alarm-f1c20',
    authDomain: 'fortune-alarm-f1c20.firebaseapp.com',
    databaseURL: 'https://fortune-alarm-f1c20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fortune-alarm-f1c20.firebasestorage.app',
    measurementId: 'G-2TNPSQ0EGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJf6e7L60I7uhQCHzlycEAOq-s6JYu8ig',
    appId: '1:857898979788:android:bdb68ccaec2cc8f72fcd69',
    messagingSenderId: '857898979788',
    projectId: 'fortune-alarm-f1c20',
    databaseURL: 'https://fortune-alarm-f1c20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fortune-alarm-f1c20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRqMA-otavjocPq0XeFMe5-Bpkr-89Tc',
    appId: '1:857898979788:ios:64fd2f8fc6fba1ea2fcd69',
    messagingSenderId: '857898979788',
    projectId: 'fortune-alarm-f1c20',
    databaseURL: 'https://fortune-alarm-f1c20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fortune-alarm-f1c20.firebasestorage.app',
    iosBundleId: 'com.seriessnap.fortuneAlarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQvXMsCQgE5freN9xHNl4qp2xmGxrdLQY',
    appId: '1:857898979788:web:ff96f74ed7e50d602fcd69',
    messagingSenderId: '857898979788',
    projectId: 'fortune-alarm-f1c20',
    authDomain: 'fortune-alarm-f1c20.firebaseapp.com',
    databaseURL: 'https://fortune-alarm-f1c20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fortune-alarm-f1c20.firebasestorage.app',
    measurementId: 'G-V95JX713RF',
  );

}